# Site settings
title: Nikos Kanakaris
description: Nikos Kanakaris's CV
favicon: /assets/img/avatar.JPG
baseurl: https://nkanak.github.io
url: https://nkanak.github.io
rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Nikos Kanakaris
  title: PhD Candidate
  address: Patras, Greece 26221
  email_1: nikos.kanakaris89@gmail.com
  email_2: nkanakaris@upnet.gr
  link: https://nkanak.github.io
  github: nkanak
  gavatar: /resumecard/assets/img/avatar.JPG
  workHistory:
    - work1:
      companyTitle: University of Patras
      companyLink: http://www.upatras.gr/en
      location: Patras, Greece
      title: Software Research Engineer
      started: 2017
      duration: (December 2017 - present)
      type: Full-time
      technologies: Python, Python Eve, Flask, Django, MongoDB, Cytoscape.js, Neo4j, graph databases, knowledge graphs, discourse graphs, discourse representation, argumentation, personalization algorithms, recommender systems, machine learning techniques, data clustering
      links:
        - link1:
          title: MyCorridor
          url: http://www.mycorridor.eu
        - link2:
          title: OpenBio-C
          url: https://www.openbio.eu
      topics:
        - topic2:
          description: Designing and implementing the collaboration and discourse environment for OpenBioC research project
        - topic1:
          description: Implementing the personalization and user profiling algorithms for MyCorridor

    - work2:
      companyTitle: Programize LLC
      companyLink: https://www.programize.com
      location: Athens, Greece
      title: Software Engineer
      started: 2016
      duration: (May 2016 - August 2017)
      type: Full-time
      technologies: Python, JavaScript, C#, C++, AngularJS, Flask, NodeJS, Apache Cordova, MySQL, BHO IE
      links:
        - link1:
          title: Litta
          url: http://litta.co
        - link2:
          title: Global Showcases
          url: http://www.globalshowcases.com
        - link3:
          title: VForVacation 
          url: http://www.vforvacation.com
        - link4:
          title: SunPower
          url: https://us.sunpower.com
        - link5:
          title: OnionID
          url: https://www.onionid.com
      topics:
        - topic1:
          description: Implementing the back-end system for Litta mobile application
        - topic2:
          description: Implementing the main mobile hybrid and back-end application for Global Showcases
        - topic3:
          description: Adding responsive functionality to the official website for VForVacation
        - topic4:
          description: Contributing to the front-end and back-end internal financial application for SunPower
        - topic5:
          description: Implementing an Internet Explorer extension for OnionID
    - work3:
      companyTitle: Programize LLC
      companyLink: https://www.programize.com
      location: Athens, Greece
      title: Software Engineer
      started: 2016
      duration: (February 2016 - May 2016)
      type: Part-time
      technologies: Python, scipy, py2exe
      topics:
        - topic1:
          description: Converting an already existing financial model from Microsoft Excel to Python
        - topic2:
          description: Contributing to the automization of the process to convert Microsoft excel workbooks to Python
    - work4:
      companyTitle: Software Competitiveness International S.A. (SoftCom International)
      companyLink: http://www.softcom-int.com
      location: Athens, Greece
      title: Junior Software Engineer
      started: 2015

      duration: (November 2015 - May 2016)
      type: Full-time
      description: "Working for a German Automotive Industry under a NDA, area: Navigation"
      technologies: C++, Python, Lua, XML, GIT, Jira, MISRA, Cmake, ISO 9001, ISO 27001
      topics:
        - topic1:
          description: Implementing the middleware component that facilitates the front-end and back-end software layers
    - work5:
      companyTitle: Software Competitiveness International S.A. (SoftCom International)
      companyLink: http://www.softcom-int.com
      location: Athens, Greece
      title: Junior Software Engineer
      started: 2015
      duration: (July 2015 - October 2015)
      type: Internship
      description: "Working for a Space Industry under a NDA, area: preventive performance monitoring"
      technologies: C++, Java, machine learning techniques, data clustering
      links:
        - link1:
          title: Research
          url: https://drive.google.com/file/d/0B7OxYNGpEIPgY0doSXNsSmlpYU0/view
      topics:
        - topic1:
          description: Researching for an alternative algorithm for hierarchical clustering
  educationHistory:
    - education1:
      organization: Mechanical Engineering & Aeronautics, University of Patras
      degree: PhD.
      location: Patras, Greece
      major: Business intelligence, Recommender systems, Digital personal assistants, Operations research, Project management, Machine learning, Interpretable Machine learning
      started: 2018
      duration: (2018 - present)

      laboratory: Industrial Management and Information Systems
      subject: Knowledge extraction and representation using machine learning algorithms - Εξαγωγή και αναπαράσταση γνώσης με χρήση τεχνικών μηχανικής μάθησης και αξιοποίησή της από ψηφιακούς προσωπικούς βοηθούς
      supervisorName: Nikos Karacapilidis
      supervisorLink: http://imis.upatras.gr/nikos
    - education2:
      organization: Informatics & Telematics, Harokopio University of Athens
      location: Athens, Greece
      degree: BSc.
      major: Computer Software & Systems
      score: 8.5
      started: 2011
      duration: (2011 - 2016)
      thesisTitle: Parallelization of “burn scar mapping” algorithms - Παραλληλοποίηση αλγορίθμων χαρτογράφησης καμένων εκτάσεων σε δορυφορικά δεδομένα
      thesisLinkPaper: https://drive.google.com/file/d/0B7OxYNGpEIPgNjRad005c0RMQzA/view
      thesisLinkPresentation: https://drive.google.com/file/d/0B7OxYNGpEIPgS1k0TGI3eTVVdUE/view
      thesisTechnologies: Digital Image Processing, Parallel Programming, Python, MPI
      supervisorName: Dimitrios Michail 
      supervisorLink: https://www.dit.hua.gr/~michail
  languages:
    - language1:
      name: Greek
      proficiency: Native
    - language2:
      name: English
      proficiency: Fluent
  programmingSkills:
    - skill1:
      name: C/C++
    - skill2:
      name: Python
    - skill3:
      name: JavaScript/Node.js
    - skill4:
      name: Haskell
    - skill5:
      name: Java
    - skill6:
      name: LaTeX
    - skill7:
      name: PostgreSQL
    - skill8:
      name: MySQL
    - skill9:
      name: SQLite
    - skill10:
      name: Neo4j
    - skill11:
      name: Recommender Systems
    - skill12:
      name: Machine Learning
    - skill13:
      name: Data Mining
    - skill14:
      name: Natural Language Processing
    - skill15:
      name: Graph Theory
    - skill16:
      name: Knowledge Graphs
    - skill17:
      name: Knowledge Management
    - skill18:
      name: Digital Image Processing
    - skill19:
      name: Parallel Programming
    - skill20:
      name: Docker
    - skill21:
      name: Git
    - skill22:
      name: SVN
  interests:
    - interest1:
      name: graph databases
    - interest2:
      name: natural language processing
    - interest3:
      name: recommender systems
    - interest4:
      name: machine learning
    - interest5:
      name: interpretable machine learning
    - interest6:
      name: data mining
    - interest7:
      name: business intelligence
    - interest8:
      name: AI-guided project management
    - interest9:
      name: graph theory
    - interest10:
      name: algorithms
    - interest11:
      name: parallel programming
    - interest12:
      name: embedded systems
    - interest13:
      name: IoT
  hobbies:
    - hobby1:
      name: Arduino/IoT
    - hobby2:
      name: electronics
    - hobby3:
      name: RC cars
    - hobby4:
      name: motorbikes
    - hobby5:
      name: gaming
    - hobby6:
      name: basketball
    - hobby7:
      name: swimming
    - hobby8:
      name: reading books
  publicationsConferencesAndBookChapters:
    - publication1:
      text: "1. N. Kanakaris, N. Karacapilidis and A. Lazanas: On the advancement of Project Management through a flexible integration of Machine Learning and Operations Research tools. In: Proceedings of the 8th International Conference on Operations Research and Enterprise Systems (ICORES 2019), Prague, Czech Republic, February 19-21, 2019"
    - publication2:
      text: "2. A. Kanterakis, G. Iatraki, K. Pityanou, L. Koumakis, N. Kanakaris, N. Karacapilidis and G. Potamias: Towards Reproducible Bioinformatics:The OpenBio-C Scientific Workflow Environemnt. In: Proceedings of the 19th annual IEEE International Conference on Bioinformatics and Bioengineering (BIBE 2019), Athens, Greece, October 28-30, 2019"
    - publication3:
      text: "3. N. Kanakaris, N. Karacapilidis, G. Kournetas and A. Lazanas: Combining Machine Learning and Operations Research Methods to Advance the Project Management Practice. In: Parlier G., Liberatore F., Demange M. (eds), Operations Research and Enterprise Systems. Communications in Computer and Information Science, Vol. 1162. Springer, Cham, 2020, pp. 135-155, DOI: 10.1007/978-3-030-37584-3_7."
    - publication4:
      text: "4. N. Kanakaris, N. Karacapilidis and G. Kournetas: On the exploitation of textual descriptions for a better-informed task assignment process. In: Proceedings of the 9th International Conference on Operations Research and Enterprise Systems (ICORES 2020), Valletta, Malta, February 22-24, 2020, Science and Technology Publications."
    - publication5:
      text: "5. N. Giarelis, N. Kanakaris and N. Karacapilidis: On a novel representation of multiple textual documents in a single graph. In I. Czarnowski, R.J.Howlett and L.C.Jain (eds.) Intelligent Decision Technologies 2020 – Proc. of the 12th KES International Conference on Intelligent Decision Technologies (KES-IDT-20), Split, Croatia, June 17-19, 2020, Springer. (accepted)"
    - publication6:
      text: "6. N. Giarelis, N. Kanakaris and N. Karacapilidis: An innovative graph-based approach to advance feature selection from multiple textual documents (under review)."
  publicationsPostersAndAbstracts:
    - publication1:
      text: "1. N. Karacapilidis, N. Kanakaris, G. Kournetas and V. Tampakas: Advancing Project Management through the Integration of Knowledge Graph and Machine Learning Technologies. In: 30th European Conference on Operational Research (EURO 2019), Dublin, Ireland, June 23-26, 2019"
    - publication2:
      text: "2. A. Kanterakis, G. Iatraki, L. Koumakis, K. Pitianou, M. Koutoulakis, N. Kanakaris, N. Karacapilidis and G. Potamias: OpenBio-C: An Online Social Workflow Management System and Research Object Repository. In: BOSC COSI: Bioinformatics Open Source Conference (ISMB/ECCB 2019), Basel, Switzerland, July 21-25, 2019"
    - publication3:
      text: "3. A. Kanterakis, G. Iatraki, K. Pityanou, L. Koumakis, N. Kanakaris, N. Karacapilidis, G. Potamias: Towards Reproducible Bioinformatics: The OpenBio-C Workflow Management Platform"
